### ISSUE TITLE
RFE: add the ability to manage multiple secrets

### ISSUE THREAD

**Issue by raffaelespazzoli** [openlab-red/vault-secret-fetcher#1]
it should be possible to be able to retrieve multiple secret.
a possible design could be having a property of this format:
`SECRETS: <secret1-path>:<secret1-file>,<secret2-path>:<secret2-file>....`

**Comment by eye0fra** [comment]
@raffaelespazzoli please check the following pull request https://github.com/openlab-red/vault-secret-fetcher/pull/4
