### ISSUE TITLE
Vault role to use for authentication

### ISSUE THREAD

**Issue by Constantin07** [openlab-red/vault-secret-fetcher#5]
Hello, 

When authenticating from Pod in K8s to Vault I need to specify the role name to use.
I use individual role per app and each role is mapped to a policy.

Is there a way to pass the role name to use for auth?

Regards,
Constantin

**Comment by eye0fra** [comment]
Hi @Constantin07,

The vault role is configured on the vault agent config file, which is represented in K8s as 
*vault-agent-config* configMap.

You can find some examples [here]( https://github.com/openlab-red/hashicorp-vault-for-openshift/tree/master/examples) with or without mutating webhook.

Best Regards

Mattia

**Comment by Constantin07** [comment]
Thanks @eye0fra for advise,

Do you know if there is a way to pass `role` as a env. variable and not in file/ConfigMap ?

In my case it makes the thing too complex - having an individual ConfigMap per pod which I would like to avoid.

Kind Regards,
Constantin

**Comment by eye0fra** [comment]
Unfortunately no, the Vault Agent need this config file, more info here: https://www.vaultproject.io/docs/agent/index.html
It does not expose it as parameter

**Comment by eye0fra** [comment]
I forgot to tell you that if you use the mutating webhook approach, you don't need to care about the config, the webhook will create for you. Just need to set the annotation.

https://github.com/openlab-red/mutating-webhook-vault-agent

**Comment by Constantin07** [comment]
Thanks @eye0fra
